### ISSUE TITLE
Bullfrog Assistant update

### ISSUE THREAD

**Issue by k3v1nwrld** [34306/TrollStoreiPA#11]
Bullfrog Assistant isnt the latest, therefore the app does a check and requires you to update to use it.I translates this with google translate so idk how accurate it is

**Comment by 34306** [comment]
I'll check that when I have time. Ping me again if I'm not update!

**Comment by GiggleMonster** [comment]
> I'll check that when I have time. Ping me again if I'm not update!

Can you please update when you get a chance

**Comment by 34306** [comment]
Maybe it's fixed, I can export it, I'll try it again
