### ISSUE TITLE
Deezer_7.15.ipa and Reddit.2021.12.0.Lizard.v1.9.ipa Crashing

### ISSUE THREAD

**Issue by rilodroid** [34306/TrollStoreiPA#13]
After instalation both apps just crash wen try to open. Im on iPhone7, iOS 15.4 with many other tweaked apps working.

**Comment by w70t** [comment]
I want Reddit 🥲❤️‍🔥
Last update

**Comment by ham0de** [comment]
Work with my on A15 15.2

**Comment by rilodroid** [comment]
What you mean?

**Comment by 34306** [comment]
Try it again, I'm still using this normally!
