### ISSUE TITLE
ipa update!

### ISSUE THREAD

**Issue by daniielsnz** [34306/TrollStoreiPA#15]
facebook 316.0 wolf 2.1
instagram v254.0 rocket.ipa
uYouPlus_17.39.5_2.1.ipa

**Comment by GD2021** [comment]
![Uploading image.png…]()
您知道这个横幅怎样去掉吗？

**Comment by malki711** [comment]
Gg

**Comment by 34306** [comment]
I'm checking that, I'll update asap
