### ISSUE TITLE
Spotify 8.5.60 is far better than 8.7 version

### ISSUE THREAD

**Issue by gototheskinny** [34306/TrollStoreiPA#17]
[link/](https://reddit.com/r/sideloaded/comments/wjwgv0/latest_spotilife_v18_sposify_v8552_working_lyrics)
Please add this as stable option.

**Comment by Richi57** [comment]
Spotify el mejor IOS 15 LifeSpotify 8642.835 funciona el premium 👍

**Comment by gototheskinny** [comment]
This version that i mentioned has HIGHEST quality support i don't know if that version has that. If you didn't tried this version i highly recommend. I'll try 8.6 version that you mentioned if i could find it on a proper source.

**Comment by 34306** [comment]
> [link/](https://reddit.com/r/sideloaded/comments/wjwgv0/latest_spotilife_v18_sposify_v8552_working_lyrics)
> Please add this as stable option.

I'm uploading it! Thanks!
