### ISSUE TITLE
Iridium

### ISSUE THREAD

**Issue by chelaxian** [34306/TrollStoreiPA#3]
Can you update Iridium app too? It seems to be installable on non-jail but doing nothing (need foul decrypt)

**Comment by 34306** [comment]
It's seem not work on Jailed because you need root access to access these folder. It show error in the image below.
![D20FA3EF-836C-4298-957E-805CB31A6B00](https://user-images.githubusercontent.com/79745143/188783484-66c81ee0-3161-42e1-ba42-2ac4033749ad.png)
