### ISSUE TITLE
HarpyReloaded not work

### ISSUE THREAD

**Issue by ab0880** [34306/TrollStoreiPA#5]
i test on my 15.1 device ，it doesn't work，my other divice still using the Wi-Fi well 。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by 34306** [comment]
I think you should pay the tweak then repack it into iPA. I don't recommend you pirate it. Maybe if you pay for it, it should work. idk😁

**Comment by ab0880** [comment]
how to repack it into iPA？



发自我的iPhone


------------------ Original ------------------
From: Huy Nguyen ***@***.***&gt;
Date: Wed,Sep 7,2022 11:54 AM
To: 34306/TrollStoreiPA ***@***.***&gt;
Cc: ab0880 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [34306/TrollStoreiPA] HarpyReloaded not work (Issue #5)





 
I think you should pay the tweak then repack it into iPA. I don't recommend you pirate it. Maybe if you pay for it, it should work. idk😁

**Comment by ab0880** [comment]
i just know how to redeb



发自我的iPhone


------------------ Original ------------------
From: Huy Nguyen ***@***.***&gt;
Date: Wed,Sep 7,2022 11:54 AM
To: 34306/TrollStoreiPA ***@***.***&gt;
Cc: ab0880 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [34306/TrollStoreiPA] HarpyReloaded not work (Issue #5)





 
I think you should pay the tweak then repack it into iPA. I don't recommend you pirate it. Maybe if you pay for it, it should work. idk😁

**Comment by 34306** [comment]
You can extract the deb, see application, rename it to Payload and zip that. Then rename the zip to ipa. Done!
