### ISSUE TITLE
Are decryption apps possible?

### ISSUE THREAD

**Issue by k3v1nwrld** [34306/TrollStoreiPA#6]
I saw the dev of TS saying that decryption apps (bfdecrypt,crackerxi) would technically work with TrollStore.Would you try and make them work?Thanks!

**Comment by 34306** [comment]
I tried. The app can open but it cannot decrypt anything. So you don't need to try, it not works!

**Comment by Dibo5684** [comment]
i would definitely do but i dont think i can yet, but will give it a try

**Comment by k3v1nwrld** [comment]
Just update me if you can please
