### ISSUE TITLE
Localiapstore or Satella 2

### ISSUE THREAD

**Issue by Alex793** [34306/TrollStoreiPA#8]
Not an issue related, but can you think you can make a working ipa of these tweaks ?

**Comment by 34306** [comment]
Actually both of 2 tweaks are not application. But you can inject Satella Jailed into iPA. It will work with some app local their in-app purchase.

**Comment by Alex793** [comment]
> Actually both of 2 tweaks are not application. But you can inject Satella Jailed into iPA. It will work with some app local their in-app purchase.

Thanks for your reply, yes I looked this injection option, just hoped for a quicker way by directly making an ipa like the AppDowngrade ipa created from the AppAdmin tweak.
